#!/bin/bash
# Jarvis v2.0 — Mac Permissions Setup Guide

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  JARVIS — Required Mac Permissions"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Open System Settings and grant these permissions:"
echo ""
echo "1. MICROPHONE (for voice / wake word)"
echo "   System Settings → Privacy & Security → Microphone"
echo "   → Enable Terminal"
echo ""
echo "2. FULL DISK ACCESS (for iMessage reading)"
echo "   System Settings → Privacy & Security → Full Disk Access"
echo "   → Enable Terminal"
echo "   → Enable Python (if shown)"
echo ""
echo "3. ACCESSIBILITY (for Mac control via AppleScript)"
echo "   System Settings → Privacy & Security → Accessibility"
echo "   → Enable Terminal"
echo ""
echo "4. SCREEN RECORDING (for screen vision)"
echo "   System Settings → Privacy & Security → Screen Recording"
echo "   → Enable Terminal"
echo ""
echo "5. AUTOMATION (granted automatically when first used)"
echo "   → Click 'Allow' when prompted by macOS"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Opening System Settings → Privacy & Security..."
open "x-apple.systempreferences:com.apple.preference.security?Privacy"
